# Generated by Django 3.2.3 on 2023-09-06 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
