# Generated by Django 3.2.3 on 2023-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_rename_description_recipe_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Выберите фотографию готового блюда",
                upload_to="recipe/",
            ),
        ),
    ]
